create table tb_cliente
(
    id bigint generated by default as identity,
    cpf varchar(15),
    email varchar(30),
    nome varchar(25),
    primary key (id)
);

create table tb_empresa
(
    saldo numeric(38,2),
    id bigint generated by default as identity,
    cnpj varchar(35),
    email varchar(30),
    nome varchar(30),
    primary key (id)
);

create table tb_transacao
(
    valor_taxa numeric(38,2),
    valor_transacao numeric(38,2),
    cliente_id bigint, empresa_id bigint,
    id bigint generated by default as identity,
    times_tamp timestamp(6),
    tipo_transacao varchar(255)
        check (tipo_transacao in ('SAQUE','DEPOSITO')),
    primary key (id)
);

alter table if exists tb_transacao add constraint FKb5rxikvy2ufro0uvbill9qqt1 foreign key (cliente_id) references tb_cliente;
alter table if exists tb_transacao add constraint FKn1599hp21ikpq3uu6su9essfy foreign key (empresa_id) references tb_empresa;
